---
language: node_js
node_js:
  - "0.12"
  - "4.0"
  - "4.1"
  - "5.1"
  - "6.5"
install:
  - npm install -g npm@3.5.3
  - npm install -g multidep
  - npm install
sudo: false
cache:
  directories:
    - node_modules
