---
language: node_js
node_js:
  - "6.9"
  - "7"
before_script:
  - git config --global user.email "davewasmer@gmail.com"
  - git config --global user.name "Dave Wasmer"
after_success:
  - npm run coverage
  - pip install awscli
  - npm run deploy-docs
sudo: false
cache:
  directories:
    - node_modules