# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Denali
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://denali.github.com/denali" # the base hostname & protocol for your site
github_username:  denali
permalink: pretty

# Build settings
markdown: kramdown
exclude: [
  'design',
  'Gemfile',
  'Gemfile.lock',
  'Guardfile',
  'npm-debug.log',
  '.scss-lint.yml'
]

additional_version_refs: [ 'master' ]
version_aliases:
  master: 'canary'
repo: 'davewasmer/denali'

source_repo: '/Users/daw/projects/denali'
